name: release to stage

on:
  push:
    tags:
      - v**
    
    
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: release to stage
          branch: main
          base: release-target-1
          labels: auto-pr
